### PR TITLE
Work around missing libudev.so.0 with post-link symlink to libudev.so.1

### LINKED ISSUE #1: Has anybody tested if this works with Ubuntu 18.04?
My Ubuntu 18.04 builds seem to fail with

```
ImportError: libudev.so.0: cannot open shared object file: No such file or directory
```

I think it is because ubuntu uses `libudev1` and we have compiled with `libudev0`

### PR DESCRIPTION
**Pull request by ryanvolz**
Work around missing libudev.so.0 on modern Linux systems. This has been a pain for a while now, and something I've had to instruct multiple users to work around.

This adds a post-link script that checks for missing libudev.so.0 and, if missing, adds a symbolic link to the environment that points to the system's libudev.so.1. There is also a pre-unlink script that removes that symbolic link if required. And if any of that fails, it should just carry on anyway.

This is pretty hacky, but it works for me locally with my Ubuntu system. Hopefully I made it general enough to work with other distributions as well? If/when the libudev CDT gets updated (for, say, CentOS 7) this probably won't be necessary anymore, but I think it could be pretty helpful until then.

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes #1

### CODE REVIEW

**Comment by hoechenberger** [comment]
@ryanvolz Thanks for the contribution! Looks okay to me :)

**Comment by hoechenberger** [comment]
Would you like to add yourself as a maintainer too?

**Comment by ryanvolz** [comment]
I already am 😉, I just thought this one could use some looking over.

**Comment by hoechenberger** [comment]
Oh. Haha sorry :) Too much stuff going on around me :D Yeah I suggest we merge this and if users report any problems, we reconvene? ;)

**Comment by ryanvolz** [comment]
Sounds good!

**Pull request merged**
