### PR TITLE
Fix linker flags on Win

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
libftdi build still fails (https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=307202&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f) - I think this should fix it.

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by ryanvolz** [comment]
The error in the build seems to be happening before it gets to the linker flags, so I don't think this will help. It's not even finding libusb from pkg-config at this point, which is a mystery to me.

**Comment by Tobias-Fischer** [comment]
Ah, okay. I thought
```
-- Could NOT find LIBUSB (missing: LIBUSB_LIBRARIES) 
```

Indicates that it just can't find the libraries.

**Comment by ryanvolz** [comment]
Looks good as-is after all, see https://github.com/conda-forge/libftdi-feedstock/pull/1.

**Pull request closed without merging**
